# Generated by Django 2.1rc1 on 2020-11-28 03:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Comments',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30, verbose_name='昵称')),
                ('email', models.EmailField(max_length=50, verbose_name='邮箱地址')),
                ('url', models.URLField(blank=True, max_length=50, null=True, verbose_name='网址')),
                ('content', models.TextField(verbose_name='评论内容')),
                ('date_publish', models.DateTimeField(auto_now_add=True, verbose_name='评论时间')),
                ('article', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='blog.Article')),
                ('p_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='c_id', to='comments.Comments')),
            ],
            options={
                'verbose_name': '评论',
                'verbose_name_plural': '评论',
                'db_table': 'blog_comments',
            },
        ),
    ]
